### ISSUE TITLE
Build Login component

### ISSUE THREAD

**Issue by cmelthratter** [shariqs/tickets#1]

**Comment by shariqs** [comment]
A component that allows users to login/out.

Cody has added the code to Menu-Bar Component.
This is a good start, but Log-In Component needs to be its own component and then added into Menu-Bar.

Create a new file called log-in.component.ts
Include the component into MenuBarComponent by adding the selector from LogInComponent to the template in menu-bar.component.ts

**Comment by shariqs** [comment]
Nice job
