### ISSUE TITLE
Make Purchased Listings Clickable [Transaction History]

### ISSUE THREAD

**Issue by techmciver** [shariqs/tickets#54]
Within the account page, we need a way that updates the left side of the screen(The ticket ETA ( estimated time of arrival)) when a user clicks a ticket they purchased within the purchased listings

**Comment by techmciver** [comment]
This issue also correlates with issue #45 figuring out a function for the ETA of each ticket

**Comment by ako2013** [comment]
Added in https://github.com/shariqs/tickets/commit/385e19fdc1e523af5ee1866754f5dff5db9c1c68
